language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
      sudo: true

install:
    - travis_retry pip install tox
script:
    - tox
    - python setup.py install && bash test_autograph.sh
after_success:
    - tox -e coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
